---
title: "Tutorial 1: Introduction"
author: "Steve Cygu"
date: "`r format(Sys.time(), '%d %B %Y ')`"
output: html_document
#  tufte::tufte_html:
#     pandoc_args: ["--dpi", "300"]
---


## Running Python

- via **notebooks** (http://mcmaster.syzygy.ca or on your own computer)
- via **scripts** + **console** (http://mcmaster.syzygy.ca/jupyter/user-redirect/lab)


```{R opts,message=FALSE,echo=FALSE,warning=FALSE}
library("knitr")
library("reticulate")
use_python("/usr/bin/python3")
```

## Variabale assignments

 - The _equal_ sign (_=_) is used to assign values to variables
 - No explicit declaration to reserve memory space. Happens automatically when the variable is assigned
 - Variable naming principles apply e.g., `variable_name`


**Examples**

```{python var_assignment,eval=TRUE}
counter = 100 # An integer assignment
miles = 1000.0 # A floating point assignment
name = "John" # A string assignment
print(counter)
print(miles)
print(name)
```

### Multiple assignment

You can assign a single value to several variables simultaneously.

**Examples**

```{python multi_assignment,eval=TRUE}
x = y = z = 2
print(x)
```

You can also assign multiple objects to multiple variables: 

**Examples**

```{python multi_assignment2, eval=TRUE}
a, b, c = 3, 5, "John"
print(a)
print(b)
print(c)
```

**Quiz**

Given `x` and `y`, what will be the new values of `x` and `y`?

```{python, eval = FALSE}
x = 2
y = 5
x, y = y, x
```

## Standard Data Types

These include:

- Numbers

>- int
>- bool
>- float

- String
- Tuple
- Dictionary

### Numbers

Stores numeric values and are _immutable_. Numbers are created when you assign values to them

```{python numbers1, eval=TRUE}
var1 = 1
var2 = True
```

### Strings

Set of characters within quotation marks (pairs of single or double quotes)

- Slice operator `[]` and `[:]` can be used to subset strings. 
- Indexing starts at `0` in the beginning of the string and starts at `-1` from the end of the string.

**Examples**

```{python string1, eval=TRUE}
str = 'Hello World!'
print(str)							# Prints complete string
print(str[0])						# First character of the string
print(str[2:5])					# 3rd and 5th string
print(str * 2)						# Prints the string 2 times
print(str + " This is cool")	# Prints concatenated string

```

**Quiz**

Given
```
str1 = "This is our first tutorial!"
```
Using `+` operator **only**, write a code to print `This is our first tutorial! This is our first tutorial`


## Basic Operators

Python language supports the following types of operators:

- Arithmetic Operators
- Comparison (i.e., Relational) Operators
- Assignment Operators
- Logical Operators
- Bitwise Operators
- Membership Operators
- Identity Operators

### Basic Arithmetic Operators

|	Operator	| Description	|	Example	|
| --------- | ------------ | --------- |
|		+		| Addition - Adds values on either side of the operator | 20 + 10 will give 30 |
|		-		| Subtraction - Subtracts right hand operand from left hand operand | 10 - 20 will give -10 |
|		* 		| Multiplication - Multiplies values on either side of the operator | 2 * 1 will give 2 |
|		/ 		| Division - Divides left hand operand by right hand operand        | 2 / 1 will give 2 |
|		% 		| Modulus - Divides left hand operand by right hand operand and return remainder | 2 % 1 will give 0 |
|		**		| Exponent - Performs exponential (power) calculation on operators | 2 ** 1  will give 2 to the power 1 |
| 		//		|  Floor Division - The division of operands where the result is the quotient in which the digits after the decimal point are removed. | 9//2 is equal to 4 and 9.0//2.0 is equal to 4.0 |


**Examples**

Convert height in cm to meters

```{python, eval = FALSE}
height_cm = int(input("What is your height in centimeters?"))
height_meters = height_cm/100
print("Your height is ", height_meters, "meters")
```

### Logical operators

|	Operator	| Description	|	Example	|
| --------- | ------------ | --------- |
|		==		| Checks if the value of two operands is equal or not, if yes then condition becomes true. | (2 == 1) is not true. |
|		!=		| Checks if the value of two operands is equal or not, if values are not equal then condition becomes true. | (2 != 1) is true. |
|		<>		| Checks if the value of two operands is equal or not, if values are not equal then condition becomes true. | (2 <> 1) is true. This is similar to != operator. |
|		>		|  Checks if the value of left operand is greater than the value of right operand, if yes then condition becomes true. | (2 > 1) is true. |
| 		<		| Checks if the value of left operand is less than the value of right operand, if yes then condition becomes true. | (2 < 1) is no true. |
|		>= 	| Checks if the value of left operand is greater than or equal to the value of right operand, if yes then condition becomes true. | (2 >= 1) is true. |
| 		<=		| Checks if the value of left operand is less than or equal to the value of right operand, if yes then condition becomes true. | (2 <= 1) is no true. |
|		and	| Called Logical AND operator. If both the operands are true, then the condition becomes true. | (2 and 1) is true. |
| 		or		| Called Logical OR Operator. If any of the two operands are non zero, then the condition becomes true. | (2 or 1) is true. |
| 		not	| Called Logical NOT Operator. Used to reverse the logical state of its operand. If a condition is true, then Logical NOT operator will make it false. | not(2 and 1) is false |

**Quiz**

Write a script to calculate BMI, where
\[
\text{bmi} = \frac{\text{weight}}{\text{height}^2}
\]

```{python, eval = FALSE}
# getting input from the user and assigning it to user

height = float(input("Enter height in meters: "))
weight = float(input("Enter weight in kg: "))

# the formula for calculating bmi

bmi = weight/(height**2)

print("Your BMI is: ",  format(bmi), " and you are: ", end='')

#conditions
if ( bmi < 16):
   print("severely underweight")

elif (bmi >= 16 and bmi < 18.5):
   print("underweight")

elif (bmi >= 18.5 and bmi < 25):
   print("Healthy")

elif (bmi >= 25 and bmi < 30):
   print("overweight")

elif (bmi >=30):
   print("severely overweight")
```



